#!/bin/bash
clear

echo -e "\E[44;1;37m USUÁRIO        SENHA       LIMITE      VALIDADE \E[0m"
echo ""

# Remove menu se a versão não existir
[[ ! -e /bin/versao ]] && rm -rf /bin/menu

# Processa cada usuário do sistema com UID > 900
awk -F : '$3 > 900 { print $1 }' /etc/passwd | sort | grep -v "nobody" | grep -viE 'polkitd|system-' | while read users; do
    # Verifica se o usuário está no banco de dados e obtém o limite
    lim=$(grep -w "$users" "$HOME/usuarios.db" | awk '{print $2}' || echo "1")

    # Obtém a senha do usuário
    senha=$(cat /etc/SSHPlus/senha/"$users" 2>/dev/null || echo "Null")

    # Obtém e formata a validade da conta
    datauser=$(chage -l "$users" | grep -i 'co' | awk -F : '{print $2}' | xargs)
    if [ "$datauser" = "never" ]; then
        data="\033[1;33mNunca\033[0m"
    else
        dat="$(date -d "$datauser" '+%Y-%m-%d')"
        hoje="$(date +%Y-%m-%d)"
        if [ "$(date -d "$hoje" +%s)" -ge "$(date -d "$dat" +%s)" ]; then
            data="\033[1;31mVenceu\033[0m"
        else
            dias_restantes=$(( ( $(date -d "$dat" +%s) - $(date +%s) ) / 86400 ))
            data="$dias_restantes \033[1;37mDias\033[0m"
        fi
    fi

    # Formata e exibe as informações do usuário
    Usuario=$(printf ' %-15s' "$users")
    Senha=$(printf '%-13s' "$senha")
    Limite=$(printf '%-10s' "$lim")
    Data=$(printf '%-1s' "$data")
    echo -e "\033[1;33m$Usuario \033[1;37m$Senha \033[1;37m$Limite \033[1;32m$Data\033[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
done

# Calcula total de usuários, usuários online e expirados
_tuser=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
_expuser=$(cat /etc/SSHPlus/Exp 2>/dev/null || echo "0")
_onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log 2>/dev/null || echo "0")
_drp=$(ps aux | grep dropbear | grep -v grep | wc -l 2>/dev/null)
_ondrp=$(( _drp - 1 ))
_onli=$(( $_ons + $_onop + $_ondrp ))

# Verifica se o arquivo 'valor' existe antes de somar
if [ -f "$HOME/valor" ]; then
    valor_sum=$(awk '{SUM += $1} END {print SUM}' "$HOME/valor")
else
    valor_sum="0"
fi

echo -e "\033[1;33m• \033[1;36mTOTAL USUARIOS\033[1;37m $_tuser \033[1;33m• \033[1;32mONLINES\033[1;37m: $_onli \033[1;33m• \033[1;31mVENCIDOS\033[1;37m: $_expuser

echo -e "\E[44;1;37m USUÁRIO V2RAY         UUID         | USUÁRIO | VALIDADE \E[0m"
echo ""

# Lista o conteúdo do diretório /etc/SSHPlus/v2ray
if [ -d /etc/SSHPlus/v2ray ]; then
    ls -l /etc/SSHPlus/v2ray
    vt=$(ls -1 /etc/SSHPlus/v2ray | wc -l)
else
    echo "Diretório /etc/SSHPlus/v2ray não encontrado."
    vt=0
fi

echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;33m• \033[1;36mTOTAL USUARIOS\033[1;37m $vt \033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"